
home-assistant:
  configurator:
    enabled: true
  service:
    type: NodePort
  persistence: 
    enabled: false
  git:
    enabled: true
    repo: https://github.com/ahstn/smart-tings.git
  
  # extraVolumes:
  # - name: config
  #   configMap:
  #     name: ha-core